#
# Executes commands at logout.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code only if STDERR is bound to a TTY.
[[ -o INTERACTIVE && -t 2 ]] && {

SAYINGS=(
    "So long and thanks for all the fish.\n  -- Douglas Adams"
    "Good morning! And in case I don't see ya, good afternoon, good evening and goodnight.\n  --Truman Burbank"
    "Good judgement is learned by experience. Experience is learned by bad judgement.\n  --Anonymous "
    "Science and technology are great, but nothing beats fun\n  --Anonymous"
    "Be true to your work, your word, and your friend.\n  --Thoreau"
    "Dont care what you do through the game. Just make sure you win the last point.\n  -- Pete Sampras' coach to Pete (as told by Pete)"
    "Man usually avoids attributing cleverness to somebody else -- unless it is an enemy.\n  -- Albert Einstein"
    "All great achievements were done during the worst time of its creator\n  -- Anonymous"
    "First they ignore you, then they laugh at you, then they fight you, then you win.\n  --Mahatma Gandhi"
    "An expert is one who knows more and more about less and less until he knows absolutely everything about nothing\n  --Anonymous"
    "Happiness is good health and a bad memory\n  --Ingrid Bergman"
    "Today, if you are not confused, you are just not thinking clearly.\n  --Anonymous"
    "The sooner you fall behind, the more time you will have to catch up.\n  --Anonymous"
    "modesty, n.:\nBeing comfortable that others will discover your greatness\n"
    "I am not too much into figures - when I look at statistics I get nervous. I'd rather focus on getting the process right, than worry about the end result.\n  --Rahul Dravid"
    "The only thing that interferes with my learning is my education.\n  -- Albert Einstein"
    "Education is the ability to listen to almost anything without losing your temper or your self-confidence.\n  --Robert Frost "
    "Seek not to follow in the footsteps of wise men; seek what they sought.\n  --Basho"
    "Keep Cool, but Don't Freeze\n  --Hellman's Mayonnaise (from Fortune Cookies)"
    "Pascal Users:\nTo show respect for the 313th anniversary (tomorrow) of the death of Blaise Pascal, your programs will be run at half speed.\n  --(Fortune Cookies)"
    "Luck is preparation meeting opportunity\n  --Anonymous"
    "One way to make your old car run better is to look up the price of a new model.\n  -- Anonymous"
    "Strong and bitter words indicate a weak cause.\n  -- Fortune Cookies"
    "Only wimps use tape backup: _real_ men just upload their important stuff on ftp, and let the rest of the world mirror it ;)\n  -- Linus Torvalds"
    "Fortitude is the guard and support of the other virtues.\n  -- Locke"
    "Fire is the test of gold; adversity, of strong men\n-- Seneca, the Greek Philosopher"
    "Before you attempt to beat the Odds, Be sure that you could survive the Odds Beating You.\n  -- From a poster on despair.com"
    "Don't try to buy at the bottom and sell at the top. It can't be done except by liars.\n  -- Bernard Baruch\n"
    "To have a second language is to have a second soul.\n -- Charlemagne\n"
    "The limits of my language means the limits of my world.\n -- Ludwig Wittgenstein\n"
    "If people never did silly things nothing intelligent would ever get done.\n -- Ludwig Wittgenstein\n"
    "Not how the world is, but that it is, is the mystery.\b  -- Ludwig Wittgenstein\n"
    "To understand a joke, you have to belong to that parish, that community of understanding. And if you feel you belong to that community of understanding of getting that joke, then you will laugh at almost anything that reinforces your sense of belonging to that group.  -- Anthony McCarten in his TEDx talk at around 12:00\n"
    "Everybody has a plan until they get punched in the mouth.  -- Mike Tyson on his opponents’ prefight strategies\n"
    "I skate to where the puck is going to be. Not where it has been.  -- Wayne Gretzky\n"
    "If you don't have a competitive advantage, don't compete. -- Jack Welch\n"
    "CS is the field where the longer you are in it the less you know. -- Anonymous\n"
    "Most people problems can be traced back to a point of miscommunication. -- Anonymous\n"
    "It is not the critic who counts; not the man who points out how the strong man stumbles, or where the doer of deeds could have done them better. The credit belongs to the man who is actually in the arena, whose face is marred by dust and sweat and blood, who strives valiantly; who errs and comes short again and again; because there is not effort without error and shortcomings; but who does actually strive to do the deed; who knows the great enthusiasm, the great devotion, who spends himself in a worthy cause, who at the best knows in the end the triumph of high achievement and who at the worst, if he fails, at least he fails while daring greatly. So that his place shall never be with those cold and timid souls who know neither victory nor defeat.  --Theodore Roosevelt\n"
    "There is NO COST to getting things WRONG.  The COST is NOT getting them PUBLISHED.  -- Prof. Brian Nosek\n"
    "Who controls the past, controls the future.  Who controls the present, controls the past.  -- George Orwell\n"
)

# Print a randomly-chosen message:
echo $SAYINGS[$(($RANDOM % ${#SAYINGS} + 1))]

} >&2
